const mongoose = require('mongoose');
const MusicScore = require('./models/MusicScore');
const User = require('./models/User');

mongoose.connect("mongodb://localhost:27017/mozartify");

const seedDatabase = async () => {
  const userId1 = '6663a93dd0f65edd4857eb95';
  const userId2 = '666425c6199bdc6ac5074e40';

  const musicScores = [
    {
      mss_title: 'Symphony No. 5',
      mss_content: 'mss_link_11',
      mss_genre: 'Classical',
      mss_composer: 'Beethoven',
      mss_copyright: 'Public Domain',
      mss_artist: 'Beethoven',
      mss_desc: 'A powerful and dramatic symphony by Beethoven',
      mss_historical_context: 'Composed in the 19th century',
      mss_instrumentation: 'Orchestra',
      mss_key: 'C Minor',
      mss_lyrics: 'Instrumental',
      mss_date_published: new Date('1808-01-01'),
      mss_date_uploaded: new Date(),
      mss_price: 20.0,
      mss_audio: 'audio_link_11',
      ownerIds: [userId1, userId2],
    },
    {
      mss_title: 'The Four Seasons',
      mss_content: 'mss_link_12',
      mss_genre: 'Classical',
      mss_composer: 'Vivaldi',
      mss_copyright: 'Public Domain',
      mss_artist: 'Vivaldi',
      mss_desc: 'A set of four violin concertos by Vivaldi',
      mss_historical_context: 'Composed in the 18th century',
      mss_instrumentation: 'Violin and Orchestra',
      mss_key: 'E Major',
      mss_lyrics: 'Instrumental',
      mss_date_published: new Date('1725-01-01'),
      mss_date_uploaded: new Date(),
      mss_price: 25.0,
      mss_audio: 'audio_link_12',
      ownerIds: [userId1, userId2],
    },
    {
      mss_title: 'Canon in D',
      mss_content: 'mss_link_13',
      mss_genre: 'Classical',
      mss_composer: 'Pachelbel',
      mss_copyright: 'Public Domain',
      mss_artist: 'Pachelbel',
      mss_desc: 'A beautiful and widely recognized piece by Pachelbel',
      mss_historical_context: 'Composed in the 17th century',
      mss_instrumentation: 'Strings',
      mss_key: 'D Major',
      mss_lyrics: 'Instrumental',
      mss_date_published: new Date('1694-01-01'),
      mss_date_uploaded: new Date(),
      mss_price: 15.0,
      mss_audio: 'audio_link_13',
      ownerIds: [userId1, userId2],
    },
    {
      mss_title: 'Boléro',
      mss_content: 'mss_link_14',
      mss_genre: 'Classical',
      mss_composer: 'Ravel',
      mss_copyright: 'Public Domain',
      mss_artist: 'Ravel',
      mss_desc: 'A mesmerizing and repetitive orchestral piece by Ravel',
      mss_historical_context: 'Composed in the 20th century',
      mss_instrumentation: 'Orchestra',
      mss_key: 'C Major',
      mss_lyrics: 'Instrumental',
      mss_date_published: new Date('1928-01-01'),
      mss_date_uploaded: new Date(),
      mss_price: 18.0,
      mss_audio: 'audio_link_14',
      ownerIds: [userId1, userId2],
    },
    {
      mss_title: 'Hungarian Rhapsody No. 2',
      mss_content: 'mss_link_15',
      mss_genre: 'Classical',
      mss_composer: 'Liszt',
      mss_copyright: 'Public Domain',
      mss_artist: 'Liszt',
      mss_desc: 'A lively and dynamic piece by Liszt',
      mss_historical_context: 'Composed in the 19th century',
      mss_instrumentation: 'Piano',
      mss_key: 'C-sharp Minor',
      mss_lyrics: 'Instrumental',
      mss_date_published: new Date('1847-01-01'),
      mss_date_uploaded: new Date(),
      mss_price: 17.0,
      mss_audio: 'audio_link_15',
      ownerIds: [userId1, userId2],
    },
    {
      mss_title: 'Symphony No. 40',
      mss_content: 'mss_link_16',
      mss_genre: 'Classical',
      mss_composer: 'Mozart',
      mss_copyright: 'Public Domain',
      mss_artist: 'Mozart',
      mss_desc: 'A famous and influential symphony by Mozart',
      mss_historical_context: 'Composed in the 18th century',
      mss_instrumentation: 'Orchestra',
      mss_key: 'G Minor',
      mss_lyrics: 'Instrumental',
      mss_date_published: new Date('1788-01-01'),
      mss_date_uploaded: new Date(),
      mss_price: 22.0,
      mss_audio: 'audio_link_16',
      ownerIds: [userId1, userId2],
    },
    {
      mss_title: 'Eine kleine Nachtmusik',
      mss_content: 'mss_link_17',
      mss_genre: 'Classical',
      mss_composer: 'Mozart',
      mss_copyright: 'Public Domain',
      mss_artist: 'Mozart',
      mss_desc: 'A popular and delightful serenade by Mozart',
      mss_historical_context: 'Composed in the 18th century',
      mss_instrumentation: 'Strings',
      mss_key: 'G Major',
      mss_lyrics: 'Instrumental',
      mss_date_published: new Date('1787-01-01'),
      mss_date_uploaded: new Date(),
      mss_price: 20.0,
      mss_audio: 'audio_link_17',
      ownerIds: [userId1, userId2],
    },
    {
      mss_title: 'Flight of the Bumblebee',
      mss_content: 'mss_link_18',
      mss_genre: 'Classical',
      mss_composer: 'Rimsky-Korsakov',
      mss_copyright: 'Public Domain',
      mss_artist: 'Rimsky-Korsakov',
      mss_desc: 'A fast and furious piece by Rimsky-Korsakov',
      mss_historical_context: 'Composed in the 19th century',
      mss_instrumentation: 'Orchestra',
      mss_key: 'A Minor',
      mss_lyrics: 'Instrumental',
      mss_date_published: new Date('1899-01-01'),
      mss_date_uploaded: new Date(),
      mss_price: 15.0,
      mss_audio: 'audio_link_18',
      ownerIds: [userId1, userId2],
    },
    {
      mss_title: 'Swan Lake',
      mss_content: 'mss_link_19',
      mss_genre: 'Classical',
      mss_composer: 'Tchaikovsky',
      mss_copyright: 'Public Domain',
      mss_artist: 'Tchaikovsky',
      mss_desc: 'A beautiful and tragic ballet score by Tchaikovsky',
      mss_historical_context: 'Composed in the 19th century',
      mss_instrumentation: 'Orchestra',
      mss_key: 'B Minor',
      mss_lyrics: 'Instrumental',
      mss_date_published: new Date('1876-01-01'),
      mss_date_uploaded: new Date(),
      mss_price: 25.0,
      mss_audio: 'audio_link_19',
      ownerIds: [userId1, userId2],
    },
    {
      mss_title: 'The Planets, Op. 32',
      mss_content: 'mss_link_20',
      mss_genre: 'Classical',
      mss_composer: 'Holst',
      mss_copyright: 'Public Domain',
      mss_artist: 'Holst',
      mss_desc: 'A suite of seven movements by Holst',
      mss_historical_context: 'Composed in the 20th century',
      mss_instrumentation: 'Orchestra',
      mss_key: 'Various',
      mss_lyrics: 'Instrumental',
      mss_date_published: new Date('1918-01-01'),
      mss_date_uploaded: new Date(),
      mss_price: 30.0,
      mss_audio: 'audio_link_20',
      ownerIds: [userId1, userId2],
    }
  ];

  try {
    await MusicScore.insertMany(musicScores);
    console.log('Database seeded with 10 new music scores!');
    mongoose.connection.close();
  } catch (error) {
    console.error('Error seeding database:', error);
    mongoose.connection.close();
  }
};

seedDatabase();
